In [50]:
import pandas as pd
import numpy as np

In [51]:
path = "/home/jack/sampler/data/08_reporting/11 - Simulator 200 points with Interest + Coverage (normalized)/increased_data.csv"

In [52]:
df = pd.read_csv(path)
df

,r_ext_pAl,r_ext_pMeO,pAl_richness,Pg_f,Tg_Tmax,sim_time,Pg_f_hat,Tg_Tmax_hat,std,interest,coverage
0,0.998455,0.752775,0.832825,0.439480,0.861510,NaN,NaN,NaN,NaN,NaN,NaN
1,0.884572,0.995134,0.489310,0.590641,0.910139,NaN,NaN,NaN,NaN,NaN,NaN
2,0.773458,0.891320,0.651214,0.499086,0.883874,NaN,NaN,NaN,NaN,NaN,NaN
3,0.513232,0.514477,0.939324,0.321652,0.782492,NaN,NaN,NaN,NaN,NaN,NaN
4,0.304354,0.935717,0.096649,0.685096,0.909678,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
295,0.070500,0.814139,0.208426,0.287017,0.650126,25.000575,0.293472,0.637852,0.684524,0.114383,0.0
296,0.071742,0.465603,0.183253,0.312714,0.663947,25.000818,0.295406,0.605133,0.619962,0.162088,0.0
297,0.133646,0.531250,0.482029,0.247170,0.624225,25.000320,0.262173,0.612996,0.465825,0.278873,0.0
298,0.174916,0.462056,0.518675,0.284974,0.644785,25.000053,0.285395,0.643081,0.365401,0.309209,0.0
299,0.234837,0.432848,0.625000,0.292023,0.668388,25.000216,0.288788,0.654127,0.332093,0.328055,0.0

In [53]:
p = catalog.load('parameters')

features=p["features"]
targets=p["targets"]
additional_values = p["additional_values"]
names=p["names"]

[02/29/24 13:12:33] INFO     Loading data from 'parameters' (MemoryDataSet)...                  ]8;id=226528;file:///home/jack/miniconda3/envs/sampler/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=316174;file:///home/jack/miniconda3/envs/sampler/lib/python3.10/site-packages/kedro/io/data_catalog.py#343\343]8;;\

In [54]:
targets_hat = [t + '_hat' for t in targets]
print("Targets:", targets)
print("Targets_hat:", targets_hat)

Targets: ['Pg_f', 'Tg_Tmax']
Targets_hat: ['Pg_f_hat', 'Tg_Tmax_hat']

In [55]:
results = df[targets + targets_hat].dropna().reset_index(drop=True)
results

         Pg_f   Tg_Tmax  Pg_f_hat  Tg_Tmax_hat
0    0.279198  0.675718  0.278098     0.716604
1    0.587360  0.910510  0.586484     0.910291
2    0.271329  0.651600  0.282267     0.708161
3    0.278129  0.721351  0.278602     0.749832
4    0.278106  0.721433  0.278607     0.749838
..        ...       ...       ...          ...
195  0.287017  0.650126  0.293472     0.637852
196  0.312714  0.663947  0.295406     0.605133
197  0.247170  0.624225  0.262173     0.612996
198  0.284974  0.644785  0.285395     0.643081
199  0.292023  0.668388  0.288788     0.654127

[200 rows x 4 columns]

In [56]:
chunk_size = 100
num_chunks = len(results) // chunk_size

for i in range(num_chunks):
    start_idx = i * chunk_size
    end_idx = (i + 1) * chunk_size
    chunk_df = results.iloc[start_idx:end_idx]
    # print(start_idx, end_idx)
    # print(chunk_df)
    mse_list = []
    for col, col_hat in zip(targets, targets_hat):
        #mse = mean_squared_error(chunk_df[col], chunk_df[col_hat])
        mse = ((chunk_df[col] - chunk_df[col_hat]) ** 2).mean()
        mse_list.append(mse)
    
    # Print MSE for each target and its _hat variation
    print(f"{100 + (i+1)*chunk_size} "+"-"*50)
    for col, col_hat, mse in zip(targets, targets_hat, mse_list):
        print(f"{100 + (i+1)*chunk_size} - MSE for {col} and {col_hat}: {mse:.2e}")

200 --------------------------------------------------
200 - MSE for Pg_f and Pg_f_hat: 9.30e-03
200 - MSE for Tg_Tmax and Tg_Tmax_hat: 2.97e-02
300 --------------------------------------------------
300 - MSE for Pg_f and Pg_f_hat: 5.49e-03
300 - MSE for Tg_Tmax and Tg_Tmax_hat: 1.84e-02

In [57]:
# Compute Mean Squared Error between columns
mse = ((results[targets] - results[targets_hat]))
mse

     Pg_f  Pg_f_hat  Tg_Tmax  Tg_Tmax_hat
0     NaN       NaN      NaN          NaN
1     NaN       NaN      NaN          NaN
2     NaN       NaN      NaN          NaN
3     NaN       NaN      NaN          NaN
4     NaN       NaN      NaN          NaN
..    ...       ...      ...          ...
195   NaN       NaN      NaN          NaN
196   NaN       NaN      NaN          NaN
197   NaN       NaN      NaN          NaN
198   NaN       NaN      NaN          NaN
199   NaN       NaN      NaN          NaN

[200 rows x 4 columns]